export const carsList = [
    {
        "id":1,
        "company":"Renault",
        "title":"Renault clio",
        "fuel": "Dizel",
        "transmition":"Automatik",
        "door_number":"4",
        "seats_number":"5",
        "air_conditioner":"Da",
        "quatro_drive":"",
        "imageUrl":"../../assets/car_images/1.jpg"
    },
    {
        "id":2,
        "company":"Renault",
        "title":"Renault clio",
        "fuel": "Dizel",
        "transmition":"Manuelni",
        "door_number":"4",
        "seats_number":"5",
        "air_conditioner":"Da",
        "quatro_drive":"",
        "imageUrl":"../../assets/car_images/2.jpg"
    },
    {
        "id":3,
        "company":"Toyota",
        "title":"Toyota Yago",
        "fuel": "Benzin",
        "transmition":"Manuelni",
        "door_number":"4",
        "seats_number":"4",
        "air_conditioner":"Da",
        "quatro_drive":"",
        "imageUrl":"../../assets/car_images/3.jpg"
    },
    {
        "id":4,
        "company":"Mercedes",
        "title":"Mercedes B kalsa",
        "fuel": "Dizel",
        "transmition":"Automatik",
        "door_number":"4",
        "seats_number":"5",
        "air_conditioner":"Da",
        "quatro_drive":"",
        "imageUrl":"../../assets/car_images/4.jpg"
    },
    {
        "id":5,
        "company":"Toyota",
        "title":"Toyota Yaris",
        "fuel": "Benzin",
        "transmition":"Manuelni",
        "door_number":"4",
        "seats_number":"5",
        "air_conditioner":"Da",
        "quatro_drive":"",
        "imageUrl":"../../assets/car_images/5.jpg"
    },
    {
        "id":6,
        "company":"Peugeot",
        "title":"Peugeot 207",
        "fuel": "Benzin",
        "transmition":"Manuelni",
        "door_number":"4",
        "seats_number":"5",
        "air_conditioner":"Da",
        "quatro_drive":"",
        "imageUrl":"../../assets/car_images/6.jpg"
    },
    {
        "id":7,
        "company":"Volkswagen",
        "title":"Volkswagen Touran",
        "fuel": "Dizel",
        "transmition":"Automatik",
        "door_number":"4",
        "seats_number":"6+1",
        "air_conditioner":"Da",
        "quatro_drive":"",
        "imageUrl":"../../assets/car_images/7.jpg"
    },
    {
        "id":8,
        "company":"Renault",
        "title":"Renault Megan",
        "fuel": "Dizel",
        "transmition":"Manuelni",
        "door_number":"4",
        "seats_number":"5",
        "air_conditioner":"Da",
        "quatro_drive":"",
        "imageUrl":"../../assets/car_images/8.jpg"
    },
    {
        "id":9,
        "company":"Volkswagen",
        "title":"Volkswagen Touareg",
        "fuel": "Dizel",
        "transmition":"Automatik",
        "door_number":"4",
        "seats_number":"5",
        "air_conditioner":"Da",
        "quatro_drive":"Da",
        "imageUrl":"../../assets/car_images/9.jpg"
    },
    {
        "id":10,
        "company":"Mercedes",
        "title":"Mercedes B kalsa",
        "fuel": "Dizel",
        "transmition":"Automatik",
        "door_number":"4",
        "seats_number":"5",
        "air_conditioner":"Da",
        "quatro_drive":"",
        "imageUrl":"../../assets/car_images/10.jpg"
    },
    {
        "id":11,
        "company":"Renault",
        "title":"Renault clio",
        "fuel": "Dizel",
        "transmition":"Manuelni",
        "door_number":"4",
        "seats_number":"5",
        "air_conditioner":"Da",
        "quatro_drive":"",
        "imageUrl":"../../assets/car_images/11.jpg"
    },
    {
        "id":12,
        "company":"Renault",
        "title":"Renault Trafic - Kombi",
        "fuel": "Dizel",
        "transmition":"Manuelni",
        "door_number":"4",
        "seats_number":"8+1",
        "air_conditioner":"Da",
        "quatro_drive":"",
        "imageUrl":"../../assets/car_images/12.jpg"
    },
    {
        "id":13,
        "company":"Toyota",
        "title":"Toyota Yaris",
        "fuel": "Benzin",
        "transmition":"Manuelni",
        "door_number":"4",
        "seats_number":"5",
        "air_conditioner":"Da",
        "quatro_drive":"",
        "imageUrl":"../../assets/car_images/13.jpg"
    },
]